---

# Install epel repo
- name: Install EPEL repository
  yum:
    name: epel-release
    state: latest

# Install git, ansible, docker
- name: Install a list of packages
  yum:
    name:
      - git
      - ansible
      - docker
    state: latest

- name: Ensure docker deamon is running
  service:
    name: docker
    state: started
  become: true

# Install pip with easy_install
- name: Install pip
  easy_install:
    name: pip
    state: latest

# Install pip packages:
- name: Install pip managed packages
  pip:
    name: "{{ item }}"
    state: latest
  loop:
    - docker

# Add Media mount to FStab
- name: Mount NAS Media folder to /mnt/Media
  mount:
      state: mounted
      path: /mnt/Media 
      src: nas:/volume1/Media
      fstype: nfs

# Create users & groups
- name: Create users
  user:
    name: "{{ item }}"
    state: present
    comment: "{{ item }} user"
    groups: "docker"
    append: yes
  loop:
    - sabnzbd
    - sonarr
    - radarr


# Setup application data folders
- name: Create application folders
  file:
    path: "/opt/{{ item }}"
    state: directory
    owner: "{{ item }}"
    group: docker
    mode: '755'
  loop:
    - sabnzbd
    - sonarr
    - radarr


# Pull docker images for sabnzbd, sonarr, radarr
- name: Pull docker images for sabnzbd, sonarr, radarr
  docker_image:
    name: "{{ item }}"
    source: pull
  loop:
    - linuxserver/sabnzbd
    - linuxserver/sonarr
    - linuxserver/radarr


# Setup paramaters for all of the above


# Create containers for the above


# Run containers
#- name: Ensure My docker container is running
#  docker_container:
#    name: testing
#    image: busybox
#    state: started
#  become: true

