---

# Install epel repo

- name: Install EPEL repository
  yum:
    name: epel-release
    state: latest

# Install git, ansible, docker
- name: Install a list of packages
  yum:
    name:
      - git
      - ansible
      - docker
    state: present


# Add Media mount to FStab
#mount -t nfs nas:/volume1/Media /mnt/Media

- name: Mount NAS Media folder to /mnt/Media
  mount:
      state: mounted
      path: /mnt/Media 
      src: nas:/volume1/Media
      fstype: nfs

# Create users & groups
- name: Create users
  user:
    name: "{{ item }}"
    state: present
    comment: "{{ item }} user"
    groups: "docker"
    append: yes
  loop:
    - sabnzbd
    - sonarr
    - radarr


# Setup application data folders

- name: Create application folders
  file:
    path: "/opt/{{ item }}"
    state: directory
    owner: "{{ item }}"
    group: docker
    mode: '755'
  loop:
    - sabnzbd
    - sonarr
    - radarr



# Pull images for
# sabnzbd
# sonarr
# radarr


# Setup paramaters for all of the above


# Create containers for the above


# Run containers


